version: '3.8'

services:
  authorization-service:
    build: ./AuthService
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/authdb
      - SPRING_DATASOURCE_USERNAME=auth_user
      - SPRING_DATASOURCE_PASSWORD=auth_pass
    networks:
      - chat-network
    depends_on:
      - auth-db

  chat-service:
    build: ./ChatService
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://chat-db:5432/chatdb
      - SPRING_DATASOURCE_USERNAME=chat_user
      - SPRING_DATASOURCE_PASSWORD=chat_pass
    networks:
      - chat-network
    depends_on:
      - chat-db

  auth-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: authdb
    ports:
      - "5433:5432"  # Отличный порт, чтобы не конфликтовать с chat-db
    networks:
      - chat-network
    volumes:
      - auth-db-data:/var/lib/postgresql/data

  chat-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: chat_user
      POSTGRES_PASSWORD: chat_pass
      POSTGRES_DB: chatdb
    ports:
      - "5432:5432"
    networks:
      - chat-network
    volumes:
      - chat-db-data:/var/lib/postgresql/data

networks:
  chat-network:
    driver: bridge

volumes:
  auth-db-data:
  chat-db-data:
